<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $modules = [
            [
                'module_key' => 'pos',
                'module_name' => 'Point of Sale (POS)',
                'description' => 'Complete POS system with inventory management, sales tracking, and reporting',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 49.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'ecommerce',
                'module_name' => 'eCommerce',
                'description' => 'Full-featured online store with product management, cart, checkout, and payment integration',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 79.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'crm',
                'module_name' => 'Customer Relationship Management (CRM)',
                'description' => 'Manage customer relationships, leads, deals, and sales pipeline',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 59.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'inventory',
                'module_name' => 'Inventory Management',
                'description' => 'Track stock levels, manage warehouses, and automate reordering',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 39.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'hrm',
                'module_name' => 'HR & Staff Management',
                'description' => 'Manage employees, departments, attendance, payroll, and leave requests',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 29.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'finance',
                'module_name' => 'Finance & Reports',
                'description' => 'Tax management, multi-currency, sales analytics and business intelligence reports',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 39.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'notifications',
                'module_name' => 'Notification Center',
                'description' => 'In-app notifications with templates, broadcast messaging and alert management',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 19.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'manufacturing',
                'module_name' => 'Manufacturing & BOM',
                'description' => 'Manage Bill of Materials, production orders, and manufacturing workflows',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 69.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'tracking',
                'module_name' => 'GTM & Tracking Proxy',
                'description' => 'Server-side GTM proxy and conversion tracking management',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 29.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'marketing',
                'module_name' => 'Marketing Campaigns',
                'description' => 'Multi-channel marketing suite supporting Email and WhatsApp broadcasts',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 49.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'automotive',
                'module_name' => 'Automotive',
                'description' => 'Vehicle listings, service bookings, and fleet management',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 59.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'healthcare',
                'module_name' => 'Healthcare',
                'description' => 'Patient records, doctor scheduling, and clinic management',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 69.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'education',
                'module_name' => 'Education',
                'description' => 'School management, student records, and classroom tracking',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 49.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'lms',
                'module_name' => 'LMS',
                'description' => 'Course builder, student progress, and learning management system',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 39.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'fitness',
                'module_name' => 'Fitness',
                'description' => 'Gym membership, class scheduling, and trainer management',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 29.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'restaurant',
                'module_name' => 'Restaurant',
                'description' => 'Menu management, table reservations, and kitchen display system',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 59.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'salon',
                'module_name' => 'Salon & Spa',
                'description' => 'Appointment booking, stylist management, and service catalog',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 39.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'realestate',
                'module_name' => 'Real Estate',
                'description' => 'Property sales, lead management, and agency tools',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 69.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'landlord',
                'module_name' => 'Landlord',
                'description' => 'Property management, tenant tracking, and rent collection',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 49.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'travel',
                'module_name' => 'Travel & Tours',
                'description' => 'Itinerary builder, booking management, and tour packages',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 59.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'freelancer',
                'module_name' => 'Freelancer',
                'description' => 'Project tracking, invoicing, and client management for freelancers',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 19.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'zatca',
                'module_name' => 'ZATCA E-Invoicing',
                'description' => 'Saudi ZATCA Phase 2 compliance and e-invoicing integration',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00, // Core for Saudi
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'marketplace',
                'module_name' => 'Multi-Vendor Marketplace',
                'description' => 'Allow multiple sellers to list products, manage commissions and payouts.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 49.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'flash-sales',
                'module_name' => 'Flash Sales & Affiliate',
                'description' => 'Time-limited sales events and affiliate marketing tracking.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00, // Part of Business/Pro
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'whatsapp',
                'module_name' => 'WhatsApp Commerce',
                'description' => 'Sell products and send updates via WhatsApp.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00, // Core for South Asia / MENA
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'loyalty',
                'module_name' => 'Loyalty & Rewards',
                'description' => 'Points system and tiered rewards for retention.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00, // Part of Business
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'branches',
                'module_name' => 'Branch Management',
                'description' => 'Multi-branch support and inventory transfer.',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 29.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'expenses',
                'module_name' => 'Expense Tracker',
                'description' => 'Track business expenses and approval workflows.',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 15.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'maroof',
                'module_name' => 'Maroof Verification',
                'description' => 'Saudi Maroof integration for store trust.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'national-address',
                'module_name' => 'National Address (SPL)',
                'description' => 'Saudi Post integration for address lookup.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'sadad',
                'module_name' => 'SADAD Payment',
                'description' => 'Saudi SADAD bill presentment integration.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'analytics',
                'module_name' => 'Analytics Engine',
                'description' => 'Deep business intelligence and reporting.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'app-marketplace',
                'module_name' => 'App Marketplace',
                'description' => 'Extension system for third-party integrations.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'reviews',
                'module_name' => 'Reviews & Ratings',
                'description' => 'Product reviews, star ratings, and photo reviews.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'security',
                'module_name' => 'Audit Logs & Security',
                'description' => 'Detailed activity tracking and security logs.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'contracts',
                'module_name' => 'Contract Management',
                'description' => 'Digital signatures and contract templates.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'events',
                'module_name' => 'Event Management',
                'description' => 'Ticketing, guest list and venue coordination.',
                'version' => '1.0.0',
                'is_active' => true,
                'price' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'erp',
                'module_name' => 'ERP Module',
                'description' => 'Enterprise Resource Planning for managing core business processes in real-time',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 79.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'purchase-orders',
                'module_name' => 'Purchase Orders',
                'description' => 'Advanced purchase order workflows with approvals and supplier portals',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 19.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'warehouse',
                'module_name' => 'Warehouse Management',
                'description' => 'Advanced warehouse management with bins, zones, and picking lists',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 29.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_key' => 'gdpr',
                'module_name' => 'GDPR Compliance',
                'description' => 'Tools for data privacy, cookie consent, and GDPR compliance',
                'version' => '1.0.0',
                'is_active' => true,
                'is_core' => false,
                'module_type' => 'marketplace',
                'price' => 19.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($modules as $module) {
            $data = $module;
            $slug = $data['module_key'];
            unset($data['module_key']);
            $data['slug'] = $slug;
            
            if (isset($data['module_name'])) {
                $name = $data['module_name'];
                unset($data['module_name']);
                $data['name'] = $name;
            }

            DB::table('modules')->updateOrInsert(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
